/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MydailyskincareroutineBlogsPureBeautyOverridesProps = {
    MydailyskincareroutineBlogsPureBeauty?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 212"?: PrimitiveOverrideProps<ViewProps>;
    "My daily skin care routine"?: PrimitiveOverrideProps<TextProps>;
    "Group 470"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 211"?: PrimitiveOverrideProps<ViewProps>;
    "Group 463"?: PrimitiveOverrideProps<ViewProps>;
    ADDRESS?: PrimitiveOverrideProps<TextProps>;
    "13 Brinkley Circuit Palmerston"?: PrimitiveOverrideProps<TextProps>;
    "Group 466"?: PrimitiveOverrideProps<ViewProps>;
    "SOCIAL MEDIA"?: PrimitiveOverrideProps<TextProps>;
    "noun-cart-4755022 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector115?: PrimitiveOverrideProps<IconProps>;
    "noun-profile-1051452 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector117?: PrimitiveOverrideProps<IconProps>;
    "Group 467"?: PrimitiveOverrideProps<ViewProps>;
    "ALL RIGHTS RESERVED."?: PrimitiveOverrideProps<TextProps>;
    "Mask group"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1"?: PrimitiveOverrideProps<ViewProps>;
    "shutterstock_1543602824 1"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 2"?: PrimitiveOverrideProps<ViewProps>;
    "By admin Posted January 7, 2022 In Face, Skin"?: PrimitiveOverrideProps<TextProps>;
    Clensing?: PrimitiveOverrideProps<TextProps>;
    "I\u2019m sharing a few tips and basics around how I use our range. We\u2019ve been getting a few questions lately \u2013 which is great because it means people are switching to more natural products like the Facial Oil Cleanser and wanting to know exactly how to use it. So I\u2019m going to share a little about my daily and weekly skincare routine about how I use our products, along with a little info or helpful tips of the product and what it\u2019s good for etc. It\u2019s important to remember that everyone\u2019s skin is so individual. What works for you may not work for others and vice versa. There are also so many things which can affect our skin health \u2013 stress, hormones, hydration, diet, environmental factors, products etc the list goes on. So this is my guide to using our range, but if you like to use it another way or have any tips of your own, please share \u2013 I love hearing new ways of how you our beautiful customers use their products. Starting at the beginning and some say the most crucial to good skin. This is the first thing I notice is slacking in my routine if my skin is looking a little dull or having breakouts (along with diet and hormones). While I\u2019ve been wearing less and less makeup the past year, cleansing at night can become a bit of a missed or lazy step. Now especially with summer and the festive season upon us, family gatherings, parties etc. it normally means more makeup and sunscreen so ensuring all makeup is removed at night helps your skin breathe, absorb product and regenerate during sleep."?: PrimitiveOverrideProps<TextProps>;
    "AM \u2013 most mornings in the shower I will use our Gentle Foaming Cleanser. Other mornings (if I\u2019ve showered at night) or running out the door for a walk or swim, it\u2019s a once over with a few spritzes of our face mist and a wipe over with a warm damp face cloth. PM \u2013 Time to double cleanse. This helps with taking off makeup/sunscreen, the ocean/sun/day with our Facial Cleansing Oil. Around 3-5 pumps. Being quite liberal with this to give skin a good facial massage and help the oil bind to all makeup and dirt. When you\u2019re ready to remove, wet a flannel/face cloth with warm/hot water and wipe off. I like to then use the Gentle Foaming Cleanser as the second cleanse to remove any residual oil and dirt. After cleansing it\u2019s onto our face mist & toner. Our Rose and Geranium Face Mist adds hydration, balances and prepares the skin for our moisturising products \u2013 especially oils. (It\u2019s also amazing for a ton of other things too \u2013 helps to set makeup, great for after sun or in the esky at the beach, around 3pm or heading out after work, in aircon etc. for more info read here.)"?: PrimitiveOverrideProps<TextProps>;
    "Group 34382"?: PrimitiveOverrideProps<ViewProps>;
    Group5128?: PrimitiveOverrideProps<ViewProps>;
    Vector5129?: PrimitiveOverrideProps<IconProps>;
    Vector5130?: PrimitiveOverrideProps<IconProps>;
    Vector5131?: PrimitiveOverrideProps<IconProps>;
    Vector5132?: PrimitiveOverrideProps<IconProps>;
    Vector5133?: PrimitiveOverrideProps<IconProps>;
    Vector5134?: PrimitiveOverrideProps<IconProps>;
    Vector5135?: PrimitiveOverrideProps<IconProps>;
    Vector5136?: PrimitiveOverrideProps<IconProps>;
    Group5137?: PrimitiveOverrideProps<ViewProps>;
    Group5138?: PrimitiveOverrideProps<ViewProps>;
    Vector5139?: PrimitiveOverrideProps<IconProps>;
    Vector5140?: PrimitiveOverrideProps<IconProps>;
    Vector5141?: PrimitiveOverrideProps<IconProps>;
    Vector5142?: PrimitiveOverrideProps<IconProps>;
    Vector5143?: PrimitiveOverrideProps<IconProps>;
    Vector5144?: PrimitiveOverrideProps<IconProps>;
    Vector5145?: PrimitiveOverrideProps<IconProps>;
    Vector5146?: PrimitiveOverrideProps<IconProps>;
    Vector5147?: PrimitiveOverrideProps<IconProps>;
    Vector5148?: PrimitiveOverrideProps<IconProps>;
    Group5149?: PrimitiveOverrideProps<ViewProps>;
    Vector5150?: PrimitiveOverrideProps<IconProps>;
    Vector5151?: PrimitiveOverrideProps<IconProps>;
    Vector5152?: PrimitiveOverrideProps<IconProps>;
    Vector5153?: PrimitiveOverrideProps<IconProps>;
    Vector5154?: PrimitiveOverrideProps<IconProps>;
    Vector5155?: PrimitiveOverrideProps<IconProps>;
    Vector5156?: PrimitiveOverrideProps<IconProps>;
    Vector5157?: PrimitiveOverrideProps<IconProps>;
    "Group 460"?: PrimitiveOverrideProps<ViewProps>;
    "\u00A9 2022 PURE BEAUTY. POWERED BY"?: PrimitiveOverrideProps<TextProps>;
    "Group 231"?: PrimitiveOverrideProps<ViewProps>;
    Layer_1?: PrimitiveOverrideProps<ViewProps>;
    Vector5224?: PrimitiveOverrideProps<IconProps>;
    Vector5225?: PrimitiveOverrideProps<IconProps>;
    Vector5226?: PrimitiveOverrideProps<IconProps>;
    Vector5227?: PrimitiveOverrideProps<IconProps>;
    Vector5228?: PrimitiveOverrideProps<IconProps>;
    Vector5229?: PrimitiveOverrideProps<IconProps>;
    Vector5230?: PrimitiveOverrideProps<IconProps>;
    Vector5231?: PrimitiveOverrideProps<IconProps>;
    Vector5232?: PrimitiveOverrideProps<IconProps>;
    Vector5233?: PrimitiveOverrideProps<IconProps>;
    Layer_2?: PrimitiveOverrideProps<ViewProps>;
    Vector5235?: PrimitiveOverrideProps<IconProps>;
    "Group 34381"?: PrimitiveOverrideProps<ViewProps>;
    Group5237?: PrimitiveOverrideProps<ViewProps>;
    Vector5238?: PrimitiveOverrideProps<IconProps>;
    Vector5239?: PrimitiveOverrideProps<IconProps>;
    Vector5240?: PrimitiveOverrideProps<IconProps>;
    Vector5241?: PrimitiveOverrideProps<IconProps>;
    Vector5242?: PrimitiveOverrideProps<IconProps>;
    Vector5243?: PrimitiveOverrideProps<IconProps>;
    Vector5244?: PrimitiveOverrideProps<IconProps>;
    Vector5245?: PrimitiveOverrideProps<IconProps>;
    Group5246?: PrimitiveOverrideProps<ViewProps>;
    Group5247?: PrimitiveOverrideProps<ViewProps>;
    Vector5248?: PrimitiveOverrideProps<IconProps>;
    Vector5249?: PrimitiveOverrideProps<IconProps>;
    Vector5250?: PrimitiveOverrideProps<IconProps>;
    Vector5251?: PrimitiveOverrideProps<IconProps>;
    Vector5252?: PrimitiveOverrideProps<IconProps>;
    Vector5253?: PrimitiveOverrideProps<IconProps>;
    Vector5254?: PrimitiveOverrideProps<IconProps>;
    Vector5255?: PrimitiveOverrideProps<IconProps>;
    Vector5256?: PrimitiveOverrideProps<IconProps>;
    Vector5257?: PrimitiveOverrideProps<IconProps>;
    Group5258?: PrimitiveOverrideProps<ViewProps>;
    Vector5259?: PrimitiveOverrideProps<IconProps>;
    Vector5260?: PrimitiveOverrideProps<IconProps>;
    Vector5261?: PrimitiveOverrideProps<IconProps>;
    Vector5262?: PrimitiveOverrideProps<IconProps>;
    Vector5263?: PrimitiveOverrideProps<IconProps>;
    Vector5264?: PrimitiveOverrideProps<IconProps>;
    Vector5265?: PrimitiveOverrideProps<IconProps>;
    Vector5266?: PrimitiveOverrideProps<IconProps>;
    "Group 34380"?: PrimitiveOverrideProps<ViewProps>;
    Login?: PrimitiveOverrideProps<TextProps>;
    "solar:logout-outline"?: PrimitiveOverrideProps<ViewProps>;
    Group13237?: PrimitiveOverrideProps<ViewProps>;
    Vector13238?: PrimitiveOverrideProps<IconProps>;
    Vector13239?: PrimitiveOverrideProps<IconProps>;
    "Group 34385"?: PrimitiveOverrideProps<ViewProps>;
    Shop?: PrimitiveOverrideProps<TextProps>;
    "heroicons:shopping-bag"?: PrimitiveOverrideProps<ViewProps>;
    Vector13243?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type MydailyskincareroutineBlogsPureBeautyProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: MydailyskincareroutineBlogsPureBeautyOverridesProps | undefined | null;
}>;
export default function MydailyskincareroutineBlogsPureBeauty(props: MydailyskincareroutineBlogsPureBeautyProps): React.ReactElement;
